version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports: 
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo_nest
    volumes:
      - demo_nest:/var/lib/mysql
volumes:
  demo_nest:
